function do_it {

  rm $1 

}

do_it client/bootstrap.js
do_it client/bootstrap.js.map
do_it client/cache-worker/CacheManager.js
do_it client/cache-worker/CacheManager.js.map
do_it client/cache-worker/cache-worker.js
do_it client/cache-worker/cache-worker.js.map
do_it client/cache-worker/shared-worker/shared-worker.js
do_it client/cache-worker/shared-worker/shared-worker.js.map
do_it client/environments/environment.js
do_it client/environments/environment.js.map
do_it client/environments/environment.prod.js
do_it client/environments/environment.prod.js.map
do_it client/mocks/data/MockAnalysis.js
do_it client/mocks/data/MockAnalysis.js.map
do_it client/mocks/data/MockDataModel.js
do_it client/mocks/data/MockDataModel.js.map
do_it client/mocks/data/MockItem.js
do_it client/mocks/data/MockItem.js.map
do_it client/mocks/data/MockKoheseType.js
do_it client/mocks/data/MockKoheseType.js.map
do_it client/mocks/data/MockUser.js
do_it client/mocks/data/MockUser.js.map
do_it client/mocks/data/MockViewData.js
do_it client/mocks/data/MockViewData.js.map
do_it client/mocks/services/MockAnalysisService.js
do_it client/mocks/services/MockAnalysisService.js.map
do_it client/mocks/services/MockAuthenticationService.js
do_it client/mocks/services/MockAuthenticationService.js.map
do_it client/mocks/services/MockCurrentUserService.js
do_it client/mocks/services/MockCurrentUserService.js.map
do_it client/mocks/services/MockDataProcessingService.js
do_it client/mocks/services/MockDataProcessingService.js.map
do_it client/mocks/services/MockDialogService.js
do_it client/mocks/services/MockDialogService.js.map
do_it client/mocks/services/MockDynamicTypesService.js
do_it client/mocks/services/MockDynamicTypesService.js.map
do_it client/mocks/services/MockImportService.js
do_it client/mocks/services/MockImportService.js.map
do_it client/mocks/services/MockItemRepository.js
do_it client/mocks/services/MockItemRepository.js.map
do_it client/mocks/services/MockLensService.js
do_it client/mocks/services/MockLensService.js.map
do_it client/mocks/services/MockNavigationService.js
do_it client/mocks/services/MockNavigationService.js.map
do_it client/mocks/services/MockProjectService.js
do_it client/mocks/services/MockProjectService.js.map
do_it client/mocks/services/MockSessionService.js
do_it client/mocks/services/MockSessionService.js.map
do_it client/mocks/services/MockStateService.js
do_it client/mocks/services/MockStateService.js.map
do_it client/mocks/services/MockVersionControlService.js
do_it client/mocks/services/MockVersionControlService.js.map
do_it client/polyfills.js
do_it client/polyfills.js.map
do_it client/src/app-routing.module.js
do_it client/src/app-routing.module.js.map
do_it client/src/app.component.js
do_it client/src/app.component.js.map
do_it client/src/app.component.spec.js
do_it client/src/app.component.spec.js.map
do_it client/src/app.module.js
do_it client/src/app.module.js.map
do_it client/src/classes/NavigationComponent.class.js
do_it client/src/classes/NavigationComponent.class.js.map
do_it client/src/classes/ProxyFilter.class.js
do_it client/src/classes/ProxyFilter.class.js.map
do_it client/src/classes/UDT/KoheseType.class.js
do_it client/src/classes/UDT/KoheseType.class.js.map
do_it client/src/classes/UDT/KoheseType.class.spec.js
do_it client/src/classes/UDT/KoheseType.class.spec.js.map
do_it client/src/components/action-table/action-table.component.js
do_it client/src/components/action-table/action-table.component.js.map
do_it client/src/components/action-table/action-table.component.spec.js
do_it client/src/components/action-table/action-table.component.spec.js.map
do_it client/src/components/action-table/action-table.module.js
do_it client/src/components/action-table/action-table.module.js.map
do_it client/src/components/action-table/editable-cell/editable-cell.component.js
do_it client/src/components/action-table/editable-cell/editable-cell.component.js.map
do_it client/src/components/action-table/editable-cell/editable-cell.component.spec.js
do_it client/src/components/action-table/editable-cell/editable-cell.component.spec.js.map
do_it client/src/components/admin/admin.component.js
do_it client/src/components/admin/admin.component.js.map
do_it client/src/components/admin/admin.component.spec.js
do_it client/src/components/admin/admin.component.spec.js.map
do_it client/src/components/admin/admin.module.js
do_it client/src/components/admin/admin.module.js.map
do_it client/src/components/admin/repositories/repositories.component.js
do_it client/src/components/admin/repositories/repositories.component.js.map
do_it client/src/components/admin/repositories/repositories.component.spec.js
do_it client/src/components/admin/repositories/repositories.component.spec.js.map
do_it client/src/components/analysis/AnalysisViewComponent.class.js
do_it client/src/components/analysis/AnalysisViewComponent.class.js.map
do_it client/src/components/analysis/analysis.component.js
do_it client/src/components/analysis/analysis.component.js.map
do_it client/src/components/analysis/analysis.component.spec.js
do_it client/src/components/analysis/analysis.component.spec.js.map
do_it client/src/components/analysis/analysis.module.js
do_it client/src/components/analysis/analysis.module.js.map
do_it client/src/components/analysis/phrase-view/phrase-view.component.js
do_it client/src/components/analysis/phrase-view/phrase-view.component.js.map
do_it client/src/components/analysis/phrase-view/phrase-view.component.spec.js
do_it client/src/components/analysis/phrase-view/phrase-view.component.spec.js.map
do_it client/src/components/analysis/sentence-view/sentence-view.component.js
do_it client/src/components/analysis/sentence-view/sentence-view.component.js.map
do_it client/src/components/analysis/sentence-view/sentence-view.component.spec.js
do_it client/src/components/analysis/sentence-view/sentence-view.component.spec.js.map
do_it client/src/components/analysis/term-view/term-view.component.js
do_it client/src/components/analysis/term-view/term-view.component.js.map
do_it client/src/components/analysis/term-view/term-view.component.spec.js
do_it client/src/components/analysis/term-view/term-view.component.spec.js.map
do_it client/src/components/app-frame/app-bar/appbar.component.js
do_it client/src/components/app-frame/app-bar/appbar.component.js.map
do_it client/src/components/app-frame/app-bar/appbar.component.spec.js
do_it client/src/components/app-frame/app-bar/appbar.component.spec.js.map
do_it client/src/components/app-frame/app-frame.module.js
do_it client/src/components/app-frame/app-frame.module.js.map
do_it client/src/components/app-frame/side-bar/sidebar.component.js
do_it client/src/components/app-frame/side-bar/sidebar.component.js.map
do_it client/src/components/app-frame/side-bar/sidebar.component.spec.js
do_it client/src/components/app-frame/side-bar/sidebar.component.spec.js.map
do_it client/src/components/compare-items/compare-items.component.js
do_it client/src/components/compare-items/compare-items.component.js.map
do_it client/src/components/compare-items/compare-items.component.spec.js
do_it client/src/components/compare-items/compare-items.component.spec.js.map
do_it client/src/components/compare-items/compare-items.module.js
do_it client/src/components/compare-items/compare-items.module.js.map
do_it client/src/components/create-wizard/create-wizard.component.js
do_it client/src/components/create-wizard/create-wizard.component.js.map
do_it client/src/components/create-wizard/create-wizard.component.spec.js
do_it client/src/components/create-wizard/create-wizard.component.spec.js.map
do_it client/src/components/create-wizard/create-wizard.module.js
do_it client/src/components/create-wizard/create-wizard.module.js.map
do_it client/src/components/create-wizard/import/import.component.js
do_it client/src/components/create-wizard/import/import.component.js.map
do_it client/src/components/create-wizard/import/import.component.spec.js
do_it client/src/components/create-wizard/import/import.component.spec.js.map
do_it client/src/components/dashboard/assignment-dashboard/AssignmentCard.class.js
do_it client/src/components/dashboard/assignment-dashboard/AssignmentCard.class.js.map
do_it client/src/components/dashboard/assignment-dashboard/active-assignment/active-assignment.component.js
do_it client/src/components/dashboard/assignment-dashboard/active-assignment/active-assignment.component.js.map
do_it client/src/components/dashboard/assignment-dashboard/active-assignment/active-assignment.component.spec.js
do_it client/src/components/dashboard/assignment-dashboard/active-assignment/active-assignment.component.spec.js.map
do_it client/src/components/dashboard/assignment-dashboard/assignment-dashboard.component.js
do_it client/src/components/dashboard/assignment-dashboard/assignment-dashboard.component.js.map
do_it client/src/components/dashboard/assignment-dashboard/assignment-dashboard.component.spec.js
do_it client/src/components/dashboard/assignment-dashboard/assignment-dashboard.component.spec.js.map
do_it client/src/components/dashboard/assignment-dashboard/completed-assignment/completed-assignment.component.js
do_it client/src/components/dashboard/assignment-dashboard/completed-assignment/completed-assignment.component.js.map
do_it client/src/components/dashboard/assignment-dashboard/completed-assignment/completed-assignment.component.spec.js
do_it client/src/components/dashboard/assignment-dashboard/completed-assignment/completed-assignment.component.spec.js.map
do_it client/src/components/dashboard/assignment-dashboard/dependency-info/dependency-info.component.js
do_it client/src/components/dashboard/assignment-dashboard/dependency-info/dependency-info.component.js.map
do_it client/src/components/dashboard/assignment-dashboard/due-assignment/due-assignment.component.js
do_it client/src/components/dashboard/assignment-dashboard/due-assignment/due-assignment.component.js.map
do_it client/src/components/dashboard/assignment-dashboard/due-assignment/due-assignment.component.spec.js
do_it client/src/components/dashboard/assignment-dashboard/due-assignment/due-assignment.component.spec.js.map
do_it client/src/components/dashboard/assignment-dashboard/editable-field/editable-field.component.js
do_it client/src/components/dashboard/assignment-dashboard/editable-field/editable-field.component.js.map
do_it client/src/components/dashboard/dashboard-selector/dashboard-selector.component.js
do_it client/src/components/dashboard/dashboard-selector/dashboard-selector.component.js.map
do_it client/src/components/dashboard/dashboard-selector/dashboard-selector.component.spec.js
do_it client/src/components/dashboard/dashboard-selector/dashboard-selector.component.spec.js.map
do_it client/src/components/dashboard/dashboard.component.js
do_it client/src/components/dashboard/dashboard.component.js.map
do_it client/src/components/dashboard/dashboard.component.spec.js
do_it client/src/components/dashboard/dashboard.component.spec.js.map
do_it client/src/components/dashboard/dashboard.module.js
do_it client/src/components/dashboard/dashboard.module.js.map
do_it client/src/components/dashboard/project-dashboard/project-dashboard.component.js
do_it client/src/components/dashboard/project-dashboard/project-dashboard.component.js.map
do_it client/src/components/dashboard/project-dashboard/project-dashboard.component.spec.js
do_it client/src/components/dashboard/project-dashboard/project-dashboard.component.spec.js.map
do_it client/src/components/dashboard/project-dashboard/project-overview/project-overview.component.js
do_it client/src/components/dashboard/project-dashboard/project-overview/project-overview.component.js.map
do_it client/src/components/dashboard/project-dashboard/project-overview/project-overview.component.spec.js
do_it client/src/components/dashboard/project-dashboard/project-overview/project-overview.component.spec.js.map
do_it client/src/components/dashboard/project-dashboard/project-selector/project-selector.component.js
do_it client/src/components/dashboard/project-dashboard/project-selector/project-selector.component.js.map
do_it client/src/components/dashboard/project-dashboard/project-selector/project-selector.component.spec.js
do_it client/src/components/dashboard/project-dashboard/project-selector/project-selector.component.spec.js.map
do_it client/src/components/dashboard/project-dashboard/user-statistics/user-statistics.component.js
do_it client/src/components/dashboard/project-dashboard/user-statistics/user-statistics.component.js.map
do_it client/src/components/dashboard/project-dashboard/user-statistics/user-statistics.component.spec.js
do_it client/src/components/dashboard/project-dashboard/user-statistics/user-statistics.component.spec.js.map
do_it client/src/components/dashboard/user-dashboard/user-dashboard.component.js
do_it client/src/components/dashboard/user-dashboard/user-dashboard.component.js.map
do_it client/src/components/dashboard/user-dashboard/user-dashboard.component.spec.js
do_it client/src/components/dashboard/user-dashboard/user-dashboard.component.spec.js.map
do_it client/src/components/details/ProxyDetails.Class.js
do_it client/src/components/details/ProxyDetails.Class.js.map
do_it client/src/components/details/children-tab/children-tab.component.js
do_it client/src/components/details/children-tab/children-tab.component.js.map
do_it client/src/components/details/children-tab/children-tab.component.spec.js
do_it client/src/components/details/children-tab/children-tab.component.spec.js.map
do_it client/src/components/details/children-tab/children-table/children-table.component.js
do_it client/src/components/details/children-tab/children-table/children-table.component.js.map
do_it client/src/components/details/children-tab/children-table/children-table.component.spec.js
do_it client/src/components/details/children-tab/children-table/children-table.component.spec.js.map
do_it client/src/components/details/children-tab/proxy-selector-tree/proxy-selector-tree.component.js
do_it client/src/components/details/children-tab/proxy-selector-tree/proxy-selector-tree.component.js.map
do_it client/src/components/details/children-tab/proxy-selector-tree/proxy-selector-tree.component.spec.js
do_it client/src/components/details/children-tab/proxy-selector-tree/proxy-selector-tree.component.spec.js.map
do_it client/src/components/details/details-dialog/details-dialog.component.js
do_it client/src/components/details/details-dialog/details-dialog.component.js.map
do_it client/src/components/details/details-dialog/details-dialog.component.spec.js
do_it client/src/components/details/details-dialog/details-dialog.component.spec.js.map
do_it client/src/components/details/details-form/details-form.component.js
do_it client/src/components/details/details-form/details-form.component.js.map
do_it client/src/components/details/details-form/details-form.component.spec.js
do_it client/src/components/details/details-form/details-form.component.spec.js.map
do_it client/src/components/details/details.component.js
do_it client/src/components/details/details.component.js.map
do_it client/src/components/details/details.component.spec.js
do_it client/src/components/details/details.component.spec.js.map
do_it client/src/components/details/details.module.js
do_it client/src/components/details/details.module.js.map
do_it client/src/components/details/history-tab/history-tab.component.js
do_it client/src/components/details/history-tab/history-tab.component.js.map
do_it client/src/components/details/history-tab/history-tab.component.spec.js
do_it client/src/components/details/history-tab/history-tab.component.spec.js.map
do_it client/src/components/details/journal/journal-entry/journal-entry.component.js
do_it client/src/components/details/journal/journal-entry/journal-entry.component.js.map
do_it client/src/components/details/journal/journal-entry/journal-entry.component.spec.js
do_it client/src/components/details/journal/journal-entry/journal-entry.component.spec.js.map
do_it client/src/components/details/journal/journal.component.js
do_it client/src/components/details/journal/journal.component.js.map
do_it client/src/components/details/journal/journal.component.spec.js
do_it client/src/components/details/journal/journal.component.spec.js.map
do_it client/src/components/details/references-tab/reference-table/reference-table.component.js
do_it client/src/components/details/references-tab/reference-table/reference-table.component.js.map
do_it client/src/components/details/references-tab/references-tab.component.js
do_it client/src/components/details/references-tab/references-tab.component.js.map
do_it client/src/components/document-view/document-view.component.js
do_it client/src/components/document-view/document-view.component.js.map
do_it client/src/components/document-view/document-view.component.spec.js
do_it client/src/components/document-view/document-view.component.spec.js.map
do_it client/src/components/document-view/document-view.module.js
do_it client/src/components/document-view/document-view.module.js.map
do_it client/src/components/explore/explore.component.js
do_it client/src/components/explore/explore.component.js.map
do_it client/src/components/explore/explore.component.spec.js
do_it client/src/components/explore/explore.component.spec.js.map
do_it client/src/components/explore/explore.module.js
do_it client/src/components/explore/explore.module.js.map
do_it client/src/components/lens/commit-browser/commit-browser.component.js
do_it client/src/components/lens/commit-browser/commit-browser.component.js.map
do_it client/src/components/lens/history-lens/history-lens.component.js
do_it client/src/components/lens/history-lens/history-lens.component.js.map
do_it client/src/components/lens/lens.component.js
do_it client/src/components/lens/lens.component.js.map
do_it client/src/components/lens/lens.module.js
do_it client/src/components/lens/lens.module.js.map
do_it client/src/components/login/login.component.js
do_it client/src/components/login/login.component.js.map
do_it client/src/components/login/login.component.spec.js
do_it client/src/components/login/login.component.spec.js.map
do_it client/src/components/login/login.module.js
do_it client/src/components/login/login.module.js.map
do_it client/src/components/tree/tree-row.class.js
do_it client/src/components/tree/tree-row.class.js.map
do_it client/src/components/tree/tree-row.component.js
do_it client/src/components/tree/tree-row.component.js.map
do_it client/src/components/tree/tree-row.component.spec.js
do_it client/src/components/tree/tree-row.component.spec.js.map
do_it client/src/components/tree/tree.component.js
do_it client/src/components/tree/tree.component.js.map
do_it client/src/components/tree/tree.component.spec.js
do_it client/src/components/tree/tree.component.spec.js.map
do_it client/src/components/tree/tree.module.js
do_it client/src/components/tree/tree.module.js.map
do_it client/src/components/type-editor/icon-selector/icon-selector.component.js
do_it client/src/components/type-editor/icon-selector/icon-selector.component.js.map
do_it client/src/components/type-editor/icon-selector/icon-selector.component.spec.js
do_it client/src/components/type-editor/icon-selector/icon-selector.component.spec.js.map
do_it client/src/components/type-editor/property-editor/property-editor.component.js
do_it client/src/components/type-editor/property-editor/property-editor.component.js.map
do_it client/src/components/type-editor/property-editor/property-editor.component.spec.js
do_it client/src/components/type-editor/property-editor/property-editor.component.spec.js.map
do_it client/src/components/type-editor/type-editor.component.js
do_it client/src/components/type-editor/type-editor.component.js.map
do_it client/src/components/type-editor/type-editor.component.spec.js
do_it client/src/components/type-editor/type-editor.component.spec.js.map
do_it client/src/components/type-editor/type-editor.module.js
do_it client/src/components/type-editor/type-editor.module.js.map
do_it client/src/components/type-editor/type-overview/type-overview.component.js
do_it client/src/components/type-editor/type-overview/type-overview.component.js.map
do_it client/src/components/type-editor/type-overview/type-overview.component.spec.js
do_it client/src/components/type-editor/type-overview/type-overview.component.spec.js.map
do_it client/src/components/user-input/k-date/k-date.component.js
do_it client/src/components/user-input/k-date/k-date.component.js.map
do_it client/src/components/user-input/k-markdown/k-markdown.component.js
do_it client/src/components/user-input/k-markdown/k-markdown.component.js.map
do_it client/src/components/user-input/k-markdown/markdown-cheat-sheet.component.js
do_it client/src/components/user-input/k-markdown/markdown-cheat-sheet.component.js.map
do_it client/src/components/user-input/k-proxy-selector/k-proxy-selector.component.js
do_it client/src/components/user-input/k-proxy-selector/k-proxy-selector.component.js.map
do_it client/src/components/user-input/k-proxy-selector/proxy-selector-dialog/proxy-selector-dialog.component.js
do_it client/src/components/user-input/k-proxy-selector/proxy-selector-dialog/proxy-selector-dialog.component.js.map
do_it client/src/components/user-input/k-proxy-selector/proxy-selector/proxy-selector.component.js
do_it client/src/components/user-input/k-proxy-selector/proxy-selector/proxy-selector.component.js.map
do_it client/src/components/user-input/k-proxy-selector/proxy-selector/proxy-selector.component.spec.js
do_it client/src/components/user-input/k-proxy-selector/proxy-selector/proxy-selector.component.spec.js.map
do_it client/src/components/user-input/k-select/k-select.component.js
do_it client/src/components/user-input/k-select/k-select.component.js.map
do_it client/src/components/user-input/k-state-editor/k-state-editor.component.js
do_it client/src/components/user-input/k-state-editor/k-state-editor.component.js.map
do_it client/src/components/user-input/k-state-editor/k-state-editor.component.spec.js
do_it client/src/components/user-input/k-state-editor/k-state-editor.component.spec.js.map
do_it client/src/components/user-input/k-text/k-text.component.js
do_it client/src/components/user-input/k-text/k-text.component.js.map
do_it client/src/components/user-input/k-user-selector/k-user-selector.component.js
do_it client/src/components/user-input/k-user-selector/k-user-selector.component.js.map
do_it client/src/components/user-input/user-input.class.js
do_it client/src/components/user-input/user-input.class.js.map
do_it client/src/components/user-input/user-input.module.js
do_it client/src/components/user-input/user-input.module.js.map
do_it client/src/constants/LocationMap.data.js
do_it client/src/constants/LocationMap.data.js.map
do_it client/src/material.module.js
do_it client/src/material.module.js.map
do_it client/src/pipes/highlight.pipe.js
do_it client/src/pipes/highlight.pipe.js.map
do_it client/src/pipes/map-key.pipe.js
do_it client/src/pipes/map-key.pipe.js.map
do_it client/src/pipes/pipes.module.js
do_it client/src/pipes/pipes.module.js.map
do_it client/src/pipes/pipes.spec.js
do_it client/src/pipes/pipes.spec.js.map
do_it client/src/pipes/sanitizeHtml.pipe.js
do_it client/src/pipes/sanitizeHtml.pipe.js.map
do_it client/src/pipes/truncate.pipe.js
do_it client/src/pipes/truncate.pipe.js.map
do_it client/src/services/analysis/analysis.service.js
do_it client/src/services/analysis/analysis.service.js.map
do_it client/src/services/authentication/authentication.interceptor.js
do_it client/src/services/authentication/authentication.interceptor.js.map
do_it client/src/services/authentication/authentication.module.js
do_it client/src/services/authentication/authentication.module.js.map
do_it client/src/services/authentication/authentication.service.js
do_it client/src/services/authentication/authentication.service.js.map
do_it client/src/services/data/data-processing.service.js
do_it client/src/services/data/data-processing.service.js.map
do_it client/src/services/dialog/dialog.service.js
do_it client/src/services/dialog/dialog.service.js.map
do_it client/src/services/dynamic-types/dynamic-types.service.js
do_it client/src/services/dynamic-types/dynamic-types.service.js.map
do_it client/src/services/dynamic-types/dynamic-types.service.spec.js
do_it client/src/services/dynamic-types/dynamic-types.service.spec.js.map
do_it client/src/services/import/import.service.js
do_it client/src/services/import/import.service.js.map
do_it client/src/services/item-repository/item-repository.service.js
do_it client/src/services/item-repository/item-repository.service.js.map
do_it client/src/services/lens-service/lens.service.js
do_it client/src/services/lens-service/lens.service.js.map
do_it client/src/services/navigation/NavigationUpdate.class.js
do_it client/src/services/navigation/NavigationUpdate.class.js.map
do_it client/src/services/navigation/navigation.service.js
do_it client/src/services/navigation/navigation.service.js.map
do_it client/src/services/project-service/project.service.js
do_it client/src/services/project-service/project.service.js.map
do_it client/src/services/services.module.js
do_it client/src/services/services.module.js.map
do_it client/src/services/socket/socket.service.js
do_it client/src/services/socket/socket.service.js.map
do_it client/src/services/state/state.service.js
do_it client/src/services/state/state.service.js.map
do_it client/src/services/state/state.service.spec.js
do_it client/src/services/state/state.service.spec.js.map
do_it client/src/services/user/current-user.service.js
do_it client/src/services/user/current-user.service.js.map
do_it client/src/services/user/session.service.js
do_it client/src/services/user/session.service.js.map
do_it client/src/services/user/user.module.js
do_it client/src/services/user/user.module.js.map
do_it client/src/services/version-control/version-control.service.js
do_it client/src/services/version-control/version-control.service.js.map
do_it client/src/services/version-control/version-control.service.spec.js
do_it client/src/services/version-control/version-control.service.spec.js.map
do_it client/test.js
do_it client/test.js.map
do_it common/src/KoheseModel.js
do_it common/src/KoheseModel.js.map
do_it common/src/item-cache.js
do_it common/src/item-cache.js.map
do_it common/src/item-proxy.js
do_it common/src/item-proxy.js.map
do_it common/src/tree-configuration.js
do_it common/src/tree-configuration.js.map
do_it common/tests/unit/item-proxy-spec.js
do_it common/tests/unit/item-proxy-spec.js.map
do_it scripts/test-load-commits.js
do_it scripts/test-load-commits.js.map
