/**
 *
 * $Id$
 */
package TestModel.validation;

import TestModel.Item;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link TestModel.Item}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemValidator {
	boolean validate();

	boolean validateChild(EList<Item> value);
	boolean validateName(String value);
	boolean validateChildByRef(EList<Item> value);
}
